# ===============================
# ACTIVE PROFILE
# ===============================

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# ===============================
# SERVER CONFIG
# ===============================

server.port=${SERVER_PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.application.name=API-GATEWAY


# ===============================
# EUREKA CONFIG
# ===============================

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# ===============================
# SERVICE DISCOVERY ROUTING
# ===============================

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# ===============================
# JWT CONFIG
# ===============================

jwt.secret=${JWT_SECRET}


# ===============================
# ROUTES CONFIGURATION
# ===============================

spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/customers/**

spring.cloud.gateway.routes[1].id=turf-service
spring.cloud.gateway.routes[1].uri=lb://TURF-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/turfs/**

spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**

spring.cloud.gateway.routes[3].id=booking-slots-service
spring.cloud.gateway.routes[3].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/slots/**

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**


# ===============================
# HEADER FORWARDING FIX
# ===============================

spring.cloud.gateway.default-filters[0]=PreserveHostHeader


# ===============================
# LOGGING CONFIG
# ===============================

logging.level.org.springframework.cloud.gateway=${GATEWAY_LOG_LEVEL:INFO}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:INFO}
logging.level.reactor.netty.http.client=${REACTOR_NETTY_LOG_LEVEL:INFO}


# ===============================
# CORS CONFIG
# ===============================

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}
