jwt.secret=mysecretkeymysecretkeymysecretkey123456
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.reactor.netty.http.client=DEBUG
