# Server port
server.port=8761

# Application name
spring.application.name=EUREKA-SERVER

# Disable self registration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: faster startup locally
eureka.server.wait-time-in-ms-when-sync-empty=0